# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: CC0-1.0

name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.7.4). Leave empty to use pom.xml version.'
        required: false
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build fat JAR
        run: mvn clean compile package
      
      - name: Get version and set tag
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ -n "${{ inputs.version }}" ]]; then
            VERSION="${{ inputs.version }}"
            echo "tag_name=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "tag_name=v${VERSION}" >> $GITHUB_OUTPUT
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      
      - name: Rename JAR with version
        run: cp shade/jDeepL.jar jDeepL-${{ steps.version.outputs.version }}.jar
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          files: jDeepL-${{ steps.version.outputs.version }}.jar
          generate_release_notes: true